apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-say-deployment
  labels:
    app.kubernetes.io/instance: docker-say
    backstage.io/kubernetes-id: docker-say
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: docker-say
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: docker-say
        backstage.io/kubernetes-id: docker-say
    spec:
      containers:
      - name: docker-say
        image: docker.io/thomaspoignant/hello-world-rest-json:latest
        ports:
        - containerPort: 8080