apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-say
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-say
  template:
    metadata:
      labels:
        app: docker-say
    spec:
      containers:
      - name: docker-say
        image: docker.io/thomaspoignant/hello-world-rest-json:latest
        ports:
        - containerPort: 8080